### ISSUE TITLE
Heartbeats being missed in clustered RabbitMQ

### ISSUE THREAD

**Issue by LiteWait** [proofit404/asgi_rabbitmq#22] opened 2017-12-20 14:40 UTC
Not sure if clustering has anything to do with this, but Daphne stops being able to receive messages at some point.  If I bump all the services and the applications things seem to run fine for a while, but at some point I start receiving "Error trying to receive messages:"

And see this in the log along with the stacktrace:

Closing channel (320): 'Too Many Missed Heartbeats, No reply in 120 seconds' on <LayerChannel number=1 OPEN conn=<LayerConnection OPEN socket=('10.0.1.10', 60362)->('10.0.1.10', 5672) params=<URLParameters host=conversions-web0 port=5672 virtual_host=/ ssl=False>>>
Closing channel (320): 'Too Many Missed Heartbeats, No reply in 120 seconds' on <LayerChannel number=2 OPEN conn=<LayerConnection OPEN socket=('10.0.1.10', 60362)->('10.0.1.10', 5672) params=<URLParameters host=conversions-web0 port=5672 virtual_host=/ ssl=False>>>
Closing connection (320): Too Many Missed Heartbeats, No reply in 120 seconds
Connection.close is waiting for 2 channels to close: <LayerConnection CLOSING socket=('10.0.1.10', 60362)->('10.0.1.10', 5672) params=<URLParameters host=conversions-web0 port=5672 virtual_host=/ ssl=False>>
Disconnected from RabbitMQ at conversions-web0:5672 (320): Too Many Missed Heartbeats, No reply in 120 seconds
Error trying to receive messages:

Traceback (most recent call last):
  File "manage.py", line 26, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/application/releases/r105.34.20586.887/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/opt/application/releases/r105.34.20586.887/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/application/releases/r105.34.20586.887/env/lib/python3.4/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/application/releases/r105.34.20586.887/env/lib/python3.4/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/opt/application/releases/r105.34.20586.887/env/lib/python3.4/site-packages/channels/management/commands/runworker.py", line 83, in handle
    worker.run()
  File "/opt/application/releases/r105.34.20586.887/env/lib/python3.4/site-packages/channels/worker.py", line 184, in run
    super(WorkerGroup, self).run()
  File "/opt/application/releases/r105.34.20586.887/env/lib/python3.4/site-packages/channels/worker.py", line 87, in run
    channel, content = self.channel_layer.receive_many(channels, block=True)
  File "/opt/application/releases/r105.34.20586.887/env/lib/python3.4/site-packages/asgiref/base_layer.py", line 43, in receive_many
    return self.receive(channels, block)
  File "/opt/application/releases/r105.34.20586.887/env/lib/python3.4/site-packages/asgi_rabbitmq/core.py", line 822, in receive
    return future.result()
  File "/opt/python3.4/lib/python3.4/concurrent/futures/_base.py", line 402, in result
    return self.__get_result()
  File "/opt/python3.4/lib/python3.4/concurrent/futures/_base.py", line 354, in __get_result
    raise self._exception
pika.exceptions.ConnectionClosed
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/python3.4/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/opt/python3.4/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/application/releases/r105.34.20586.887/env/lib/python3.4/site-packages/channels/worker.py", line 87, in run
    channel, content = self.channel_layer.receive_many(channels, block=True)
  File "/opt/application/releases/r105.34.20586.887/env/lib/python3.4/site-packages/asgiref/base_layer.py", line 43, in receive_many
    return self.receive(channels, block)
  File "/opt/application/releases/r105.34.20586.887/env/lib/python3.4/site-packages/asgi_rabbitmq/core.py", line 822, in receive
    return future.result()
  File "/opt/python3.4/lib/python3.4/concurrent/futures/_base.py", line 402, in result
    return self.__get_result()
  File "/opt/python3.4/lib/python3.4/concurrent/futures/_base.py", line 354, in __get_result
    raise self._exception
pika.exceptions.ConnectionClosed

**Comment by proofit404** [comment] 2017-12-22 14:55
Duplicate of https://github.com/proofit404/asgi_rabbitmq/issues/17

**Closed by proofit404** 2017-12-22 14:55 UTC
