### ISSUE TITLE
Repeated error "Error trying to receive messages:"

### ISSUE THREAD

**Issue by LiteWait** [proofit404/asgi_rabbitmq#23] opened 2017-12-22 14:52 UTC
I don't know what is causing this error, but I am seeing this across all my web servers using a rabbitmq cluster.  Error just keeps repeating over and over:

```
Excerpt from log:
Socket Error: 104
Disconnected from RabbitMQ at internal-applications-web1:5672 (-1): ConnectionResetError(104, 'Connection reset by peer')
Error trying to receive messages:
Error trying to receive messages:
Error trying to receive messages:
Error trying to receive messages:
...
```

**Comment by proofit404** [comment] 2017-12-22 14:55
Duplicate of https://github.com/proofit404/asgi_rabbitmq/issues/17

**Closed by proofit404** 2017-12-22 14:55 UTC
